/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MRouteImport } from './routes/m'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MIndexRouteImport } from './routes/m.index'
import { Route as MPulseRouteImport } from './routes/m.pulse'
import { Route as MPositionsRouteImport } from './routes/m.positions'
import { Route as MAlertsRouteImport } from './routes/m.alerts'
import { Route as AppSymbolsRouteImport } from './routes/_app.symbols'
import { Route as AppStrategiesRouteImport } from './routes/_app.strategies'
import { Route as AppSimulatorRouteImport } from './routes/_app.simulator'
import { Route as AppSignalsRouteImport } from './routes/_app.signals'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppPositionsRouteImport } from './routes/_app.positions'
import { Route as AppOverviewRouteImport } from './routes/_app.overview'
import { Route as AppKontrollsenterRouteImport } from './routes/_app.kontrollsenter'
import { Route as AppInvariantsRouteImport } from './routes/_app.invariants'
import { Route as AppAuditRouteImport } from './routes/_app.audit'
import { Route as AppAnalyticsDebugRouteImport } from './routes/_app.analytics-debug'
import { Route as AppAlertsRouteImport } from './routes/_app.alerts'
import { Route as AppAdmissionRouteImport } from './routes/_app.admission'
import { Route as MPositionsSymbolRouteImport } from './routes/m.positions_.$symbol'
import { Route as AppSymbolsSymbolRouteImport } from './routes/_app.symbols_.$symbol'
import { Route as ApiPublicHooksSnapshotSignalContextRouteImport } from './routes/api/public/hooks/snapshot-signal-context'
import { Route as ApiPublicHooksSnapshotRegimeTickRouteImport } from './routes/api/public/hooks/snapshot-regime-tick'
import { Route as ApiPublicHooksSetupSnapshotConfigRouteImport } from './routes/api/public/hooks/setup-snapshot-config'

const MRoute = MRouteImport.update({
  id: '/m',
  path: '/m',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MIndexRoute = MIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MRoute,
} as any)
const MPulseRoute = MPulseRouteImport.update({
  id: '/pulse',
  path: '/pulse',
  getParentRoute: () => MRoute,
} as any)
const MPositionsRoute = MPositionsRouteImport.update({
  id: '/positions',
  path: '/positions',
  getParentRoute: () => MRoute,
} as any)
const MAlertsRoute = MAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => MRoute,
} as any)
const AppSymbolsRoute = AppSymbolsRouteImport.update({
  id: '/symbols',
  path: '/symbols',
  getParentRoute: () => AppRoute,
} as any)
const AppStrategiesRoute = AppStrategiesRouteImport.update({
  id: '/strategies',
  path: '/strategies',
  getParentRoute: () => AppRoute,
} as any)
const AppSimulatorRoute = AppSimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => AppRoute,
} as any)
const AppSignalsRoute = AppSignalsRouteImport.update({
  id: '/signals',
  path: '/signals',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppPositionsRoute = AppPositionsRouteImport.update({
  id: '/positions',
  path: '/positions',
  getParentRoute: () => AppRoute,
} as any)
const AppOverviewRoute = AppOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AppRoute,
} as any)
const AppKontrollsenterRoute = AppKontrollsenterRouteImport.update({
  id: '/kontrollsenter',
  path: '/kontrollsenter',
  getParentRoute: () => AppRoute,
} as any)
const AppInvariantsRoute = AppInvariantsRouteImport.update({
  id: '/invariants',
  path: '/invariants',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsDebugRoute = AppAnalyticsDebugRouteImport.update({
  id: '/analytics-debug',
  path: '/analytics-debug',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)
const AppAdmissionRoute = AppAdmissionRouteImport.update({
  id: '/admission',
  path: '/admission',
  getParentRoute: () => AppRoute,
} as any)
const MPositionsSymbolRoute = MPositionsSymbolRouteImport.update({
  id: '/positions_/$symbol',
  path: '/positions/$symbol',
  getParentRoute: () => MRoute,
} as any)
const AppSymbolsSymbolRoute = AppSymbolsSymbolRouteImport.update({
  id: '/symbols_/$symbol',
  path: '/symbols/$symbol',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicHooksSnapshotSignalContextRoute =
  ApiPublicHooksSnapshotSignalContextRouteImport.update({
    id: '/api/public/hooks/snapshot-signal-context',
    path: '/api/public/hooks/snapshot-signal-context',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSnapshotRegimeTickRoute =
  ApiPublicHooksSnapshotRegimeTickRouteImport.update({
    id: '/api/public/hooks/snapshot-regime-tick',
    path: '/api/public/hooks/snapshot-regime-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSetupSnapshotConfigRoute =
  ApiPublicHooksSetupSnapshotConfigRouteImport.update({
    id: '/api/public/hooks/setup-snapshot-config',
    path: '/api/public/hooks/setup-snapshot-config',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/m': typeof MRouteWithChildren
  '/admission': typeof AppAdmissionRoute
  '/alerts': typeof AppAlertsRoute
  '/analytics-debug': typeof AppAnalyticsDebugRoute
  '/audit': typeof AppAuditRoute
  '/invariants': typeof AppInvariantsRoute
  '/kontrollsenter': typeof AppKontrollsenterRoute
  '/overview': typeof AppOverviewRoute
  '/positions': typeof AppPositionsRoute
  '/settings': typeof AppSettingsRoute
  '/signals': typeof AppSignalsRoute
  '/simulator': typeof AppSimulatorRoute
  '/strategies': typeof AppStrategiesRoute
  '/symbols': typeof AppSymbolsRoute
  '/m/alerts': typeof MAlertsRoute
  '/m/positions': typeof MPositionsRoute
  '/m/pulse': typeof MPulseRoute
  '/m/': typeof MIndexRoute
  '/symbols/$symbol': typeof AppSymbolsSymbolRoute
  '/m/positions/$symbol': typeof MPositionsSymbolRoute
  '/api/public/hooks/setup-snapshot-config': typeof ApiPublicHooksSetupSnapshotConfigRoute
  '/api/public/hooks/snapshot-regime-tick': typeof ApiPublicHooksSnapshotRegimeTickRoute
  '/api/public/hooks/snapshot-signal-context': typeof ApiPublicHooksSnapshotSignalContextRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admission': typeof AppAdmissionRoute
  '/alerts': typeof AppAlertsRoute
  '/analytics-debug': typeof AppAnalyticsDebugRoute
  '/audit': typeof AppAuditRoute
  '/invariants': typeof AppInvariantsRoute
  '/kontrollsenter': typeof AppKontrollsenterRoute
  '/overview': typeof AppOverviewRoute
  '/positions': typeof AppPositionsRoute
  '/settings': typeof AppSettingsRoute
  '/signals': typeof AppSignalsRoute
  '/simulator': typeof AppSimulatorRoute
  '/strategies': typeof AppStrategiesRoute
  '/symbols': typeof AppSymbolsRoute
  '/m/alerts': typeof MAlertsRoute
  '/m/positions': typeof MPositionsRoute
  '/m/pulse': typeof MPulseRoute
  '/m': typeof MIndexRoute
  '/symbols/$symbol': typeof AppSymbolsSymbolRoute
  '/m/positions/$symbol': typeof MPositionsSymbolRoute
  '/api/public/hooks/setup-snapshot-config': typeof ApiPublicHooksSetupSnapshotConfigRoute
  '/api/public/hooks/snapshot-regime-tick': typeof ApiPublicHooksSnapshotRegimeTickRoute
  '/api/public/hooks/snapshot-signal-context': typeof ApiPublicHooksSnapshotSignalContextRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/m': typeof MRouteWithChildren
  '/_app/admission': typeof AppAdmissionRoute
  '/_app/alerts': typeof AppAlertsRoute
  '/_app/analytics-debug': typeof AppAnalyticsDebugRoute
  '/_app/audit': typeof AppAuditRoute
  '/_app/invariants': typeof AppInvariantsRoute
  '/_app/kontrollsenter': typeof AppKontrollsenterRoute
  '/_app/overview': typeof AppOverviewRoute
  '/_app/positions': typeof AppPositionsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/signals': typeof AppSignalsRoute
  '/_app/simulator': typeof AppSimulatorRoute
  '/_app/strategies': typeof AppStrategiesRoute
  '/_app/symbols': typeof AppSymbolsRoute
  '/m/alerts': typeof MAlertsRoute
  '/m/positions': typeof MPositionsRoute
  '/m/pulse': typeof MPulseRoute
  '/m/': typeof MIndexRoute
  '/_app/symbols_/$symbol': typeof AppSymbolsSymbolRoute
  '/m/positions_/$symbol': typeof MPositionsSymbolRoute
  '/api/public/hooks/setup-snapshot-config': typeof ApiPublicHooksSetupSnapshotConfigRoute
  '/api/public/hooks/snapshot-regime-tick': typeof ApiPublicHooksSnapshotRegimeTickRoute
  '/api/public/hooks/snapshot-signal-context': typeof ApiPublicHooksSnapshotSignalContextRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/m'
    | '/admission'
    | '/alerts'
    | '/analytics-debug'
    | '/audit'
    | '/invariants'
    | '/kontrollsenter'
    | '/overview'
    | '/positions'
    | '/settings'
    | '/signals'
    | '/simulator'
    | '/strategies'
    | '/symbols'
    | '/m/alerts'
    | '/m/positions'
    | '/m/pulse'
    | '/m/'
    | '/symbols/$symbol'
    | '/m/positions/$symbol'
    | '/api/public/hooks/setup-snapshot-config'
    | '/api/public/hooks/snapshot-regime-tick'
    | '/api/public/hooks/snapshot-signal-context'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admission'
    | '/alerts'
    | '/analytics-debug'
    | '/audit'
    | '/invariants'
    | '/kontrollsenter'
    | '/overview'
    | '/positions'
    | '/settings'
    | '/signals'
    | '/simulator'
    | '/strategies'
    | '/symbols'
    | '/m/alerts'
    | '/m/positions'
    | '/m/pulse'
    | '/m'
    | '/symbols/$symbol'
    | '/m/positions/$symbol'
    | '/api/public/hooks/setup-snapshot-config'
    | '/api/public/hooks/snapshot-regime-tick'
    | '/api/public/hooks/snapshot-signal-context'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/m'
    | '/_app/admission'
    | '/_app/alerts'
    | '/_app/analytics-debug'
    | '/_app/audit'
    | '/_app/invariants'
    | '/_app/kontrollsenter'
    | '/_app/overview'
    | '/_app/positions'
    | '/_app/settings'
    | '/_app/signals'
    | '/_app/simulator'
    | '/_app/strategies'
    | '/_app/symbols'
    | '/m/alerts'
    | '/m/positions'
    | '/m/pulse'
    | '/m/'
    | '/_app/symbols_/$symbol'
    | '/m/positions_/$symbol'
    | '/api/public/hooks/setup-snapshot-config'
    | '/api/public/hooks/snapshot-regime-tick'
    | '/api/public/hooks/snapshot-signal-context'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  MRoute: typeof MRouteWithChildren
  ApiPublicHooksSetupSnapshotConfigRoute: typeof ApiPublicHooksSetupSnapshotConfigRoute
  ApiPublicHooksSnapshotRegimeTickRoute: typeof ApiPublicHooksSnapshotRegimeTickRoute
  ApiPublicHooksSnapshotSignalContextRoute: typeof ApiPublicHooksSnapshotSignalContextRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/m': {
      id: '/m'
      path: '/m'
      fullPath: '/m'
      preLoaderRoute: typeof MRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/': {
      id: '/m/'
      path: '/'
      fullPath: '/m/'
      preLoaderRoute: typeof MIndexRouteImport
      parentRoute: typeof MRoute
    }
    '/m/pulse': {
      id: '/m/pulse'
      path: '/pulse'
      fullPath: '/m/pulse'
      preLoaderRoute: typeof MPulseRouteImport
      parentRoute: typeof MRoute
    }
    '/m/positions': {
      id: '/m/positions'
      path: '/positions'
      fullPath: '/m/positions'
      preLoaderRoute: typeof MPositionsRouteImport
      parentRoute: typeof MRoute
    }
    '/m/alerts': {
      id: '/m/alerts'
      path: '/alerts'
      fullPath: '/m/alerts'
      preLoaderRoute: typeof MAlertsRouteImport
      parentRoute: typeof MRoute
    }
    '/_app/symbols': {
      id: '/_app/symbols'
      path: '/symbols'
      fullPath: '/symbols'
      preLoaderRoute: typeof AppSymbolsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/strategies': {
      id: '/_app/strategies'
      path: '/strategies'
      fullPath: '/strategies'
      preLoaderRoute: typeof AppStrategiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/simulator': {
      id: '/_app/simulator'
      path: '/simulator'
      fullPath: '/simulator'
      preLoaderRoute: typeof AppSimulatorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/signals': {
      id: '/_app/signals'
      path: '/signals'
      fullPath: '/signals'
      preLoaderRoute: typeof AppSignalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/positions': {
      id: '/_app/positions'
      path: '/positions'
      fullPath: '/positions'
      preLoaderRoute: typeof AppPositionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/overview': {
      id: '/_app/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof AppOverviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kontrollsenter': {
      id: '/_app/kontrollsenter'
      path: '/kontrollsenter'
      fullPath: '/kontrollsenter'
      preLoaderRoute: typeof AppKontrollsenterRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invariants': {
      id: '/_app/invariants'
      path: '/invariants'
      fullPath: '/invariants'
      preLoaderRoute: typeof AppInvariantsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit': {
      id: '/_app/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics-debug': {
      id: '/_app/analytics-debug'
      path: '/analytics-debug'
      fullPath: '/analytics-debug'
      preLoaderRoute: typeof AppAnalyticsDebugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/alerts': {
      id: '/_app/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admission': {
      id: '/_app/admission'
      path: '/admission'
      fullPath: '/admission'
      preLoaderRoute: typeof AppAdmissionRouteImport
      parentRoute: typeof AppRoute
    }
    '/m/positions_/$symbol': {
      id: '/m/positions_/$symbol'
      path: '/positions/$symbol'
      fullPath: '/m/positions/$symbol'
      preLoaderRoute: typeof MPositionsSymbolRouteImport
      parentRoute: typeof MRoute
    }
    '/_app/symbols_/$symbol': {
      id: '/_app/symbols_/$symbol'
      path: '/symbols/$symbol'
      fullPath: '/symbols/$symbol'
      preLoaderRoute: typeof AppSymbolsSymbolRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/hooks/snapshot-signal-context': {
      id: '/api/public/hooks/snapshot-signal-context'
      path: '/api/public/hooks/snapshot-signal-context'
      fullPath: '/api/public/hooks/snapshot-signal-context'
      preLoaderRoute: typeof ApiPublicHooksSnapshotSignalContextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/snapshot-regime-tick': {
      id: '/api/public/hooks/snapshot-regime-tick'
      path: '/api/public/hooks/snapshot-regime-tick'
      fullPath: '/api/public/hooks/snapshot-regime-tick'
      preLoaderRoute: typeof ApiPublicHooksSnapshotRegimeTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/setup-snapshot-config': {
      id: '/api/public/hooks/setup-snapshot-config'
      path: '/api/public/hooks/setup-snapshot-config'
      fullPath: '/api/public/hooks/setup-snapshot-config'
      preLoaderRoute: typeof ApiPublicHooksSetupSnapshotConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAdmissionRoute: typeof AppAdmissionRoute
  AppAlertsRoute: typeof AppAlertsRoute
  AppAnalyticsDebugRoute: typeof AppAnalyticsDebugRoute
  AppAuditRoute: typeof AppAuditRoute
  AppInvariantsRoute: typeof AppInvariantsRoute
  AppKontrollsenterRoute: typeof AppKontrollsenterRoute
  AppOverviewRoute: typeof AppOverviewRoute
  AppPositionsRoute: typeof AppPositionsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSignalsRoute: typeof AppSignalsRoute
  AppSimulatorRoute: typeof AppSimulatorRoute
  AppStrategiesRoute: typeof AppStrategiesRoute
  AppSymbolsRoute: typeof AppSymbolsRoute
  AppSymbolsSymbolRoute: typeof AppSymbolsSymbolRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdmissionRoute: AppAdmissionRoute,
  AppAlertsRoute: AppAlertsRoute,
  AppAnalyticsDebugRoute: AppAnalyticsDebugRoute,
  AppAuditRoute: AppAuditRoute,
  AppInvariantsRoute: AppInvariantsRoute,
  AppKontrollsenterRoute: AppKontrollsenterRoute,
  AppOverviewRoute: AppOverviewRoute,
  AppPositionsRoute: AppPositionsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSignalsRoute: AppSignalsRoute,
  AppSimulatorRoute: AppSimulatorRoute,
  AppStrategiesRoute: AppStrategiesRoute,
  AppSymbolsRoute: AppSymbolsRoute,
  AppSymbolsSymbolRoute: AppSymbolsSymbolRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface MRouteChildren {
  MAlertsRoute: typeof MAlertsRoute
  MPositionsRoute: typeof MPositionsRoute
  MPulseRoute: typeof MPulseRoute
  MIndexRoute: typeof MIndexRoute
  MPositionsSymbolRoute: typeof MPositionsSymbolRoute
}

const MRouteChildren: MRouteChildren = {
  MAlertsRoute: MAlertsRoute,
  MPositionsRoute: MPositionsRoute,
  MPulseRoute: MPulseRoute,
  MIndexRoute: MIndexRoute,
  MPositionsSymbolRoute: MPositionsSymbolRoute,
}

const MRouteWithChildren = MRoute._addFileChildren(MRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  MRoute: MRouteWithChildren,
  ApiPublicHooksSetupSnapshotConfigRoute:
    ApiPublicHooksSetupSnapshotConfigRoute,
  ApiPublicHooksSnapshotRegimeTickRoute: ApiPublicHooksSnapshotRegimeTickRoute,
  ApiPublicHooksSnapshotSignalContextRoute:
    ApiPublicHooksSnapshotSignalContextRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
